# Production secrets â€” fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:DU1xCLC+oaytmfs4QjWEwpm1V/hVuu9fm53G7GNb/4+kClg9HGdne3wm8BmiftSI3bwP,iv:BiWzqRuwEBQS7PQmbjw6S/oqKLYK6n2B9vH1iADm4G4=,tag:+x837yu32SE7mZxGSctkJw==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:qevIOWFHKeiR,iv:N2DIwv7h3CnEeWIZSMfvoxskcKXiDhVh4Zx2AaIZFIc=,tag:CUH2oT99u7r4lfAaG8abyA==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:+rKKD2Nxf4d2YKKE29xzwl51rE+5mdIwPaRVzRB0,iv:S1NwwXXv6UejqAxU+aiWn7/2RxXr6fUjTKW/4dbV8jc=,tag:9T/IoZYWUM/pxOa4rqahkA==,type:str]
sops:
    lastmodified: "2026-02-28T20:05:34Z"
    mac: ENC[AES256_GCM,data:D0OHZUn7YI7QKlL1ssXqq1ReOJCaPMY+AjgibneoBw6qgb2OqlRvvWMvdmtCACE9SCae8vAobWlUjhujBQASwNQLqKiAMrAMM4bnaFszfoI7tNYyBjzcDVUmvO+lzsQA5o0D/9tWPJ/6RcT4/P/aQNUflkO6onh0Hkhl3eoUkZ8=,iv:k23fNPGAzNDSVXfhXCt0PUi6umszEQe20rcYBdyftN4=,tag:+JWIfgz8IL/WJR4+c/6IUw==,type:str]
    pgp:
        - created_at: "2026-02-28T20:05:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxK+RReF/tQgAQ//a4KdEKCC9UeXOwCvhWEYx2sLrvNEzGeoFVLrxn/k4/9m
            POmGobD/L8QzJHnfoWfgZNPEOZywsb+2Ess9hLq7CUmiKMsJvEZkGtrkoSfvUd/V
            FRUrm4nH7KJw41hjiPxpzI58AWn9i4R/byy4Sj95rMi0a3MIcmhGCE5F0z98K1r1
            g5WI0vCbCauo3PjlsfMbYhf88dgsQcppBwQqZFlQxG5Z2Qt5xf3lLaenmFfvNmmm
            dZ2gC3MJjgDZg8/u/JFc5B+DhF22AiMUA8zE604Vd0EaKC3nhmVXZPM/eVxiNsKA
            BAjtclJ1CJZq1WZBt1b1KCMnvL+4Zgbh9q4QSMX6Cd2crgORlhghIzpkyQdUm28H
            /rWN9Cq95AnfCoDXTR3jqRQo6r7OfO9Rp9/1skQllxMlF/Yh377SULQWenKbBY/h
            0a7sMCg6DRQ8zjWHJ+2aUMNxE9dy/Y7fzWavFO/GxNemha/r6VGAkY7thnQAHSrI
            hoyEqUj5nNuEizSyjO0wNZx45GzJzZVet8pyZzKPFur6dYCTP2lTOxBgsfaOQB1w
            nVMaWxm7qF1kC7U5BDTw90K0HwsSHgrixxq/euxIdJPnYt2moXpqhRXZYnSO6CtZ
            9asUX3CvZpduAUeIrsb/GICbNXmSEX6Xje0Q3RPst/776CaGBDLPPJ6he2qhSzzU
            aAEJAhDAQ8ziH1g8DYDicEVyxM2TeVI2q6occr+xF+XRHDpdiTBqdmEbTKKzVHJP
            qYbSq7A1Wg07c0ft+6kDq5yytKqbqNsRFS29zrxWoNgrGVU6Jyh759bpUSCRkThr
            vXCZ8IyCm1QH
            =Xr/0
            -----END PGP MESSAGE-----
          fp: 83C72E6A377F2E76D7FBE123E2BBA1C6C85F0DC5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:LuMVvBNCx+I7,iv:z3Fe5Ue83RgV7o2r35IIAYbv68edfr79pNPCt9KXpII=,tag:9P0GxJLOxmDmjc6/kGk0hQ==,type:str]
    password: ENC[AES256_GCM,data:apiZHZ43UO+eoNS1y6Yy3lY+JOH7G3fysJfbOKGt,iv:IvIBc37CjV2WRDl/I31Y7RqQ0HBaIALgmJ3PzyXdzoM=,tag:lutxOaw+cG7juM2A03hg7g==,type:str]
sops:
    lastmodified: "2026-02-28T20:05:34Z"
    mac: ENC[AES256_GCM,data:D0OHZUn7YI7QKlL1ssXqq1ReOJCaPMY+AjgibneoBw6qgb2OqlRvvWMvdmtCACE9SCae8vAobWlUjhujBQASwNQLqKiAMrAMM4bnaFszfoI7tNYyBjzcDVUmvO+lzsQA5o0D/9tWPJ/6RcT4/P/aQNUflkO6onh0Hkhl3eoUkZ8=,iv:k23fNPGAzNDSVXfhXCt0PUi6umszEQe20rcYBdyftN4=,tag:+JWIfgz8IL/WJR4+c/6IUw==,type:str]
    pgp:
        - created_at: "2026-02-28T20:05:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxK+RReF/tQgAQ//a4KdEKCC9UeXOwCvhWEYx2sLrvNEzGeoFVLrxn/k4/9m
            POmGobD/L8QzJHnfoWfgZNPEOZywsb+2Ess9hLq7CUmiKMsJvEZkGtrkoSfvUd/V
            FRUrm4nH7KJw41hjiPxpzI58AWn9i4R/byy4Sj95rMi0a3MIcmhGCE5F0z98K1r1
            g5WI0vCbCauo3PjlsfMbYhf88dgsQcppBwQqZFlQxG5Z2Qt5xf3lLaenmFfvNmmm
            dZ2gC3MJjgDZg8/u/JFc5B+DhF22AiMUA8zE604Vd0EaKC3nhmVXZPM/eVxiNsKA
            BAjtclJ1CJZq1WZBt1b1KCMnvL+4Zgbh9q4QSMX6Cd2crgORlhghIzpkyQdUm28H
            /rWN9Cq95AnfCoDXTR3jqRQo6r7OfO9Rp9/1skQllxMlF/Yh377SULQWenKbBY/h
            0a7sMCg6DRQ8zjWHJ+2aUMNxE9dy/Y7fzWavFO/GxNemha/r6VGAkY7thnQAHSrI
            hoyEqUj5nNuEizSyjO0wNZx45GzJzZVet8pyZzKPFur6dYCTP2lTOxBgsfaOQB1w
            nVMaWxm7qF1kC7U5BDTw90K0HwsSHgrixxq/euxIdJPnYt2moXpqhRXZYnSO6CtZ
            9asUX3CvZpduAUeIrsb/GICbNXmSEX6Xje0Q3RPst/776CaGBDLPPJ6he2qhSzzU
            aAEJAhDAQ8ziH1g8DYDicEVyxM2TeVI2q6occr+xF+XRHDpdiTBqdmEbTKKzVHJP
            qYbSq7A1Wg07c0ft+6kDq5yytKqbqNsRFS29zrxWoNgrGVU6Jyh759bpUSCRkThr
            vXCZ8IyCm1QH
            =Xr/0
            -----END PGP MESSAGE-----
          fp: 83C72E6A377F2E76D7FBE123E2BBA1C6C85F0DC5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
