# Production secrets â€” fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:JkAiDqUpzj1oB8olbARILaskmR4qfvJCqrKw+/v5zSXs6cW+tG6FpK1Et9ayYOVKR7QH,iv:Yocp28KjvDg9vxzAAakrDYDhT2cCDm3KHbefx4AYsME=,tag:/FAQJEvrN5vffRQ7kjjyLA==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:qsvGh8LJ9jnQ,iv:YiXm9MLAlUdi0FZHkMD07UFFoWHSDyjkfXAfMPddb9g=,tag:miXaksscg9W2rLqDmXGy7g==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:w0AGucSz2/76sJdQ82CrfmACpj8AFxiaiDqQRUuq,iv:4Mr3iu2an2txxfY03PZdzrxqC2mUw4K/8mFx6aWOoBY=,tag:Igdyk2/f6JAdBofbSfeq4g==,type:str]
sops:
    lastmodified: "2026-02-28T20:14:09Z"
    mac: ENC[AES256_GCM,data:GfOXT+gdxLA2KYByHuEbbcFu+GfXqFbSUrh2xTA/438/8P2fsGOQFuGnrJ8Q9uGVgbgaSLyQhg1AfNe72GpMKwmR5BNYVkvZQGnzeqokM9MxlQ/IrVr1ZS7DmeHWHKm52sTUDYxBF4M8npOhlm0vL0agck7xhilOVGCxGjUAALo=,iv:iNt1gZdRRyFdh/2oUZ7TSrzQSIIxu7wQPiTaWP6iZWc=,tag:np7fQJKIfkjiWRrro1K9ng==,type:str]
    pgp:
        - created_at: "2026-02-28T20:14:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAuLxJu3eS4kH/iG3VYGeLwkCipOYJ6v2iW6heAsFpEfgb
            fIz1i3aNPi0q6eCuwg/+tsim79iovtl+7Y52IMpD8PtQ7FCWVw2P/4ETKLrjvqL3
            Ng6FSJG+ZSJyZgtZPyAW1y4b/2eZmTZqeV+lRTmMO8B66qRHmQb2gRhilaIkLrF0
            CyqtZQyF9gGhImpcC5BnwUjwsDRAEnTigZRscojTt2lAdDaeiuaTLuGxdERgr+AM
            9DXVESBffmpD9hwzDMPnCg+Tbaz4rGUzKkIoLgcnjg3QdlLcElX9ZeatSqexWm7k
            oD/KgkGA+qaKZHIapodaA4643VTU8pOspKKLnn/lcLbmtkMcp+dM3p4Iwg6bn0EI
            AiyzhGwntmcWXBTr5uHfZLJWe+mvnWoQuSPoekW/0lcuLEiBk8NazauDwgs14fnQ
            E0pA0Av9IZ5YMueiqFvV8yROBW4ZOX6SDy27QJjzz6Lim7Pjjg8daKfkC5N5tvq0
            QotXaqf09Hwaa03q2OeatklnC24QCyHWinSBPaCeGcy+aU33mwRH3jbdZfDt5gE7
            0kzKFxwnXAdwgXea7QInn9LEBg82evCIJywNw8REinVpuZxb75AWmc1PkzO2hkqC
            BsnorvF+nHxQv1YzCx5pUj5ADBy3N9z+OXSEGYzFes2BxWyr9icNMZUuaRfMoknU
            aAEJAhD2fO2o+vss52M5j3DUEUOLonWlpGc666D4YgVQJ8zAoE+B7fcJ5zCxvrMg
            wocp9raQGS9diPB+9tTdWy+RNF/9DO58gdCP/o9fM5LmDimPwD+x4Rf9yZM2ELHF
            iN5xw+3LQtaE
            =899A
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xhi9d3IDUeAT,iv:WwxmoB8vJ2jDtGT4EBz2nK7VHYWgDw1xSVDM24YqjQM=,tag:r6jqNsUfQV4qjUrDyhiMsQ==,type:str]
    password: ENC[AES256_GCM,data:lh0Uu3rTcNfZUczsJoaqNYbMsh5oTHbTvVo7Jbh9,iv:VV1qxVnhNr5w8FTcWRa8yDII8ExbXdQ/9o72TyvlULY=,tag:KmqApsDjF2P/+iF7z+ad5A==,type:str]
sops:
    lastmodified: "2026-02-28T20:14:09Z"
    mac: ENC[AES256_GCM,data:GfOXT+gdxLA2KYByHuEbbcFu+GfXqFbSUrh2xTA/438/8P2fsGOQFuGnrJ8Q9uGVgbgaSLyQhg1AfNe72GpMKwmR5BNYVkvZQGnzeqokM9MxlQ/IrVr1ZS7DmeHWHKm52sTUDYxBF4M8npOhlm0vL0agck7xhilOVGCxGjUAALo=,iv:iNt1gZdRRyFdh/2oUZ7TSrzQSIIxu7wQPiTaWP6iZWc=,tag:np7fQJKIfkjiWRrro1K9ng==,type:str]
    pgp:
        - created_at: "2026-02-28T20:14:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAuLxJu3eS4kH/iG3VYGeLwkCipOYJ6v2iW6heAsFpEfgb
            fIz1i3aNPi0q6eCuwg/+tsim79iovtl+7Y52IMpD8PtQ7FCWVw2P/4ETKLrjvqL3
            Ng6FSJG+ZSJyZgtZPyAW1y4b/2eZmTZqeV+lRTmMO8B66qRHmQb2gRhilaIkLrF0
            CyqtZQyF9gGhImpcC5BnwUjwsDRAEnTigZRscojTt2lAdDaeiuaTLuGxdERgr+AM
            9DXVESBffmpD9hwzDMPnCg+Tbaz4rGUzKkIoLgcnjg3QdlLcElX9ZeatSqexWm7k
            oD/KgkGA+qaKZHIapodaA4643VTU8pOspKKLnn/lcLbmtkMcp+dM3p4Iwg6bn0EI
            AiyzhGwntmcWXBTr5uHfZLJWe+mvnWoQuSPoekW/0lcuLEiBk8NazauDwgs14fnQ
            E0pA0Av9IZ5YMueiqFvV8yROBW4ZOX6SDy27QJjzz6Lim7Pjjg8daKfkC5N5tvq0
            QotXaqf09Hwaa03q2OeatklnC24QCyHWinSBPaCeGcy+aU33mwRH3jbdZfDt5gE7
            0kzKFxwnXAdwgXea7QInn9LEBg82evCIJywNw8REinVpuZxb75AWmc1PkzO2hkqC
            BsnorvF+nHxQv1YzCx5pUj5ADBy3N9z+OXSEGYzFes2BxWyr9icNMZUuaRfMoknU
            aAEJAhD2fO2o+vss52M5j3DUEUOLonWlpGc666D4YgVQJ8zAoE+B7fcJ5zCxvrMg
            wocp9raQGS9diPB+9tTdWy+RNF/9DO58gdCP/o9fM5LmDimPwD+x4Rf9yZM2ELHF
            iN5xw+3LQtaE
            =899A
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
