# SOPS-encrypted secrets for production
# To edit: sops k8s/overlays/production/secrets.sops.yaml
# To encrypt: sops --encrypt --in-place k8s/overlays/production/secrets.sops.yaml
# NOTE: Key names updated for Spring Boot. Values need re-encryption with SOPS after updating plaintext.
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:cQODD1e0wWRO9SrC7RaPYVX5jTbVc2a6C6yco06BKGnTUJh8GjtZbJURu7aObcNUL4ubOIJfuVLJWQIEY98POGLSkWVdGKlvplMOf11lr3ebubOwqnTSqIuuw/RF3Lieg6DTheao67M=,iv:QGMNbKqo/0mYY0KTh7havEpXoe4qnOetdLWFqbWzp9M=,tag:9PnhWz3VLu64fdSLpgf58A==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:7tKLqzT/z+ZLv4i3n1dNw+PiQaLZD15d8OihnnyK,iv:2jamijmOCa8k3Fy6ZW/ChP9It9N/eCwBPkINlE25FB4=,tag:WvQz6bF07aw8YeVtNzVSUQ==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:F7wxCMG4WieazNYuzjuVbZbSFoLA+BkDZgRMniw5KqvPSdyNf6aW04bDNxo0on0ZQPhwHa2EU5cLM7CBAsMdnXdpn0PaYk96HblKhELhsAo=,iv:cvmkgxq7rXjr9i81WESSqk/ZKCTD5xeJ+7oOtEpjZvE=,tag:jPQnBDft1FsflapBo/AS4g==,type:str]
    SPRING_MAIL_HOST: ENC[AES256_GCM,data:8uvp/l9JPjABDzpzslrlJbKhQbz3wZ+uiFF/SY8JUzPYrHTKbWSJmDKtYptpn55tB1lupXQgY39PWvTgSPP095VhBKATrLTrR3PlgpHev9VjirMwUJn42h+nJHsvi1IpAx14OIo=,iv:xzGXcy9QglnCAnp8MKakSQgL2rmawU30JvWBvSjZ6zI=,tag:SBNrCYwBUEtXQwLl5mC4rg==,type:str]
    SPRING_MAIL_FROM: ENC[AES256_GCM,data:CU4XxjyH47qvI+gg9p3zsm/eVyelUXzzkKmHXqg=,iv:PPdqRmzzbiMQessdC3gA45LwktGSv7Nqp0s2aQCrC/k=,tag:pyhRZ7tiFHYgjwxmeYakVg==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:g8wSVL29qjEafThSXaK/qvcfEdMJLB58MfXVU1+p2Zbdk716ji+ClUXY810F+Ez2eZrFPPe6DWWoEcoF4w==,iv:SBx6Sn8prgsX9vqa80F8jlVDMdiLQSi5HklqdsQn/Go=,tag:xZLfde9oiAVZET2cejz8oA==,type:str]
sops:
    lastmodified: "2026-02-13T15:02:08Z"
    mac: ENC[AES256_GCM,data:7jnUILJddhyOl6F+chUTUkio/N9h0V1fvW1J2OJ6cTMM/MpI174t64fVxk3m46yCkLjmNgTfyC13P6oMZx6FXnG/vmPEQoiytk52t9qHh8di30Z2Y+903zjAdCyWB7ZbHUmSVpsjbHQN2ZxkMBUPfsZmqjbCWWXgMkDKH4H3t54=,iv:E+2OAtl0ETYvJyyBZCfM6KcOt4HKFoV4NWNIgEBdGvM=,tag:BqS69G7m5hbhlq8QCEzP4Q==,type:str]
    pgp:
        - created_at: "2026-02-13T15:02:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxK+RReF/tQgAQ//UCvuxS+9RNBh16MYGXU6GY1fcB1L7dSqs8qpDi3EUpLb
            okQ0kSds/WRaElZyvt1ZjX/s/pcJDdTgQLphTo3t7kBtQ8abs7PS8ZKBHgePCApr
            1F2dxARsVYimKKDSQ9wDgoqlZPUQ28ClAL0vxfTjweL6MhUio6MlqjG10oZJ5vPn
            vNdiRN9i6Nryxqkkz9zvkP7LMUUazQWJFxlJjNJHYXWdfqUYwjtwwfjXQhZTyedh
            N065rAfrIPGd+ocqWKwQXatnFvxgm5SDciB6oqUbOP19YVjUQ9BMjgKZkeznQmP1
            PBia+jsmW6G2TJUyVCMhYbVfisbXnVoFKv6P0cPBDr04JLAbbLBLsqSSzRHjw8hP
            ikUcBcI10szQL9gzjryWf7X2glrylgAJx7DHtMG1jOKTsYNNsJxsbd27NX2ysjpQ
            wrkXM5B4kayI+2IccVR6vhQEeKNJ1WzKT5BiAJgQIOf3tbCNkuGsJ28DVgUFFb95
            g44itgblNmhP0ldB9UVMyoKLVjmALz3wfSM+fPnDOeT5eEb0YR+8TKjyov2IMkzU
            VewW55FTGPm/QP8h+bW5B068SebACe3I0GU8mjbeDbK+Ckk774xffQtAQHclgcXm
            01x45DPGsOJ8zjuQHQ8pGXnXyiEpbs91hkdrYK7je9zwHz1Ec91aEPTokIAVDPbU
            ZgEJAhBBKVkGDyqQ/Kz7zixZy+AtJUKSOlUwX9HSlHZHpD5LkiQeE1s6B/a9eNng
            Z8UK8Xl/SstATbv90WDWwnv8bjbg9SAaX6R5mMsNvILgfGgfbva9CdD0TEl3mEko
            EVM1tU0rGA==
            =UNqX
            -----END PGP MESSAGE-----
          fp: 83C72E6A377F2E76D7FBE123E2BBA1C6C85F0DC5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:JtTT5g==,iv:MT3JVCKQA3sKNHp5q0aGEa8e5ivHkLuo0UzZqeVtihY=,tag:s6p3B0Lz1Op/JyOU3Fv+nA==,type:str]
    password: ENC[AES256_GCM,data:WldHwGB7HbrKicXa0q5Nqwf7Op7WQ97oezu2rLI+,iv:13flSRXsofDm9W2D+Kz0aASRrRgkMzpHUWsAeOnMBwA=,tag:Sti0/tvwWEhQ5BkX6xKdiA==,type:str]
sops:
    lastmodified: "2026-02-13T15:02:08Z"
    mac: ENC[AES256_GCM,data:7jnUILJddhyOl6F+chUTUkio/N9h0V1fvW1J2OJ6cTMM/MpI174t64fVxk3m46yCkLjmNgTfyC13P6oMZx6FXnG/vmPEQoiytk52t9qHh8di30Z2Y+903zjAdCyWB7ZbHUmSVpsjbHQN2ZxkMBUPfsZmqjbCWWXgMkDKH4H3t54=,iv:E+2OAtl0ETYvJyyBZCfM6KcOt4HKFoV4NWNIgEBdGvM=,tag:BqS69G7m5hbhlq8QCEzP4Q==,type:str]
    pgp:
        - created_at: "2026-02-13T15:02:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxK+RReF/tQgAQ//UCvuxS+9RNBh16MYGXU6GY1fcB1L7dSqs8qpDi3EUpLb
            okQ0kSds/WRaElZyvt1ZjX/s/pcJDdTgQLphTo3t7kBtQ8abs7PS8ZKBHgePCApr
            1F2dxARsVYimKKDSQ9wDgoqlZPUQ28ClAL0vxfTjweL6MhUio6MlqjG10oZJ5vPn
            vNdiRN9i6Nryxqkkz9zvkP7LMUUazQWJFxlJjNJHYXWdfqUYwjtwwfjXQhZTyedh
            N065rAfrIPGd+ocqWKwQXatnFvxgm5SDciB6oqUbOP19YVjUQ9BMjgKZkeznQmP1
            PBia+jsmW6G2TJUyVCMhYbVfisbXnVoFKv6P0cPBDr04JLAbbLBLsqSSzRHjw8hP
            ikUcBcI10szQL9gzjryWf7X2glrylgAJx7DHtMG1jOKTsYNNsJxsbd27NX2ysjpQ
            wrkXM5B4kayI+2IccVR6vhQEeKNJ1WzKT5BiAJgQIOf3tbCNkuGsJ28DVgUFFb95
            g44itgblNmhP0ldB9UVMyoKLVjmALz3wfSM+fPnDOeT5eEb0YR+8TKjyov2IMkzU
            VewW55FTGPm/QP8h+bW5B068SebACe3I0GU8mjbeDbK+Ckk774xffQtAQHclgcXm
            01x45DPGsOJ8zjuQHQ8pGXnXyiEpbs91hkdrYK7je9zwHz1Ec91aEPTokIAVDPbU
            ZgEJAhBBKVkGDyqQ/Kz7zixZy+AtJUKSOlUwX9HSlHZHpD5LkiQeE1s6B/a9eNng
            Z8UK8Xl/SstATbv90WDWwnv8bjbg9SAaX6R5mMsNvILgfGgfbva9CdD0TEl3mEko
            EVM1tU0rGA==
            =UNqX
            -----END PGP MESSAGE-----
          fp: 83C72E6A377F2E76D7FBE123E2BBA1C6C85F0DC5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
