# SOPS-encrypted secrets for staging
# To edit: sops k8s/overlays/staging/secrets.sops.yaml
# To encrypt: sops --encrypt --in-place k8s/overlays/staging/secrets.sops.yaml
# NOTE: Key names updated for Spring Boot. Values need re-encryption with SOPS after updating plaintext.
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:Yc+UGXiy6QaOXgOXQDGy+8wvSpIE5dd1oTKpfMuJLEOmTv1fTAbsOjfVBfZauxhJcvT2C+45KeU603/kT0Wk3JyUZAJPmmIOHWiGr/73cLnI0WhUoaJqykdnstMK7O1H/p3pU8am,iv:jJUrji9K8gI2DbD2n5qEsOzdRaUUBWL9Cr7VL6oMOj4=,tag:w0/uW2ZixWeTRTA58LXhGg==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:wAAcsw==,iv:JdYPxt4ZJJ8oUfkEGuqntrqP3soCgdOdoTGXVBTS/TY=,tag:L24cOkn7j8O7azD+/pj1CQ==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:97zJr91M0m4L1Q==,iv:FqqI5PTMhpwk6WGm1sfJRqksa/ywHVrPQ7FnY2ogNCM=,tag:hi447+NDP41wiW/GI07zDw==,type:str]
    SPRING_MAIL_HOST: ENC[AES256_GCM,data:fz2ESiYlJaLhoSqsZbitntiIDppsQIHFLaYcNwznQR0kn+e7dFuQfeg6/zC1W8B5OkN6Sv91aF04FVu8E4SLeNqsJoGuFSOnMLxSNoBsM6jiBRBF3yDOJ3JYc9LGhc2DResy1EY=,iv:Ocd1y9297/SyKzk4/6V7CAUP/pIINRKACaoAJHLRRdE=,tag:CsPoVoOEBAnsYFihm0lRHw==,type:str]
    SPRING_MAIL_FROM: ENC[AES256_GCM,data:v1UW25I3NlA/HXhEU+DxjQ6FoQmOZoUPYCdTAnE=,iv:9jTngjRh8j0wrHGKPm90ECvXvBYcTwfDkEK3DZo+IoE=,tag:RfVtJ3grDsn/W1hgm+CqZg==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:yvOjNRGCGuhlwp6b61lPAxXUWin71lMO222rF4Mnku4Ff1cdx+AKJPDVY0rGNjp7tyTSaeBnEQIuPtHHmA==,iv:HkW8344L6FOK74zIq7EegkwbLs6K2UDrvhYMTqdzOC8=,tag:9Dk3Sr9VMQOGaQ5wot/nQw==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:OIAc1wZMQmRl88v65Izqu2UIXnCvQrv3TM8eWKie,iv:elHyhQhBX90TKCCdnksWUOv2fZEZg1JOCxqvwkblY+k=,tag:8Klg406SEK1ejfv0+Eoheg==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:wh4Mjuvf3EZcYHlgKjpF7nnssTNfM/VlaDEWEPZOuxgsQICsm6s6JOhedGmePLAheJJgMmySXx2kShingQhZ84nhx8u6/sb8/jBgJR9lTuE=,iv:DUel/mFMJaCk8sbHHkYp1MwLStsLyq3HyXOlf3u+QNY=,tag:mIfphb7GSKl8Ge2l/PTfwg==,type:str]
sops:
    lastmodified: "2026-02-15T19:33:49Z"
    mac: ENC[AES256_GCM,data:mm5asp2XDI/lrTKKUHMq1UiLsEshbkWbrvVT2MXzfW+cicxWJ3AGlXKijJGkX9jq0+3R2AEA6i4gjhhkUp1PX9txcKwZO3PN2MwvGDDDhxXmrKQUnrNJ55AXQPx0BESMzY4dRdLu7io3zbu8rJq5qVqxazPyyX3WxYsarhUEZVE=,iv:nCAdASla5vJ0uGFcu4E0xfXsiB8iCSQCcVrbEhAyfI4=,tag:D/SI/Nbb6k0QNY/lICtgJQ==,type:str]
    pgp:
        - created_at: "2026-02-15T19:33:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAvhZ+eX2HrU0YppwaK0D0NJ0I6ju01feo1yZL1CwO9xv2
            wl1gPVFM5JzAAh2E2/u5/e4AhIbu7lh3sW04WE+1MmbdFLDND9q0im522U8KbdxA
            y7BXx/rapWyznM6OEvk10dDjBg67VJg6cldcf7K/YrJyienvsuwdQnuXRzWp/pvN
            8ENOUG5LdwLoKy0ysvJvd70tMIxF21Dek30mQKWoI+SegClY5PoNoJHhcA5sfq4l
            2I/Ydpez7N42NixrQfomQq2Mp+b6d/+sEehZqOf0pdt66V0cQNX0tF2iJvm1l8Q/
            7JqFFR5gDmdthSE6Ry/emGTRPEUU8D0JY2gd8yEya9i8vzfAYni2rRGyusKlLFJw
            R+7lR7uYVj4lwH4OCDfBlARioQnLzbhCjjy+fDxcg8B9S1u+U67YWeGrNE+pKKHf
            LIowMceLDRKmivvJ2GvanBHEw2wrO/BwZ72rw2ZlJVqs6HFdVvIozSHGf48s+Roq
            o7ijetbdUDZkPWZnogdgUFFowCSlCVS1Zqq8WQQaWKwd4FHezNiMSUowYRDS+8SP
            WzFV8Lx7P86gpJEBq0u/Kqsgt7KTLOuCjeAXV4QUD0/soVZtAta+dmKkp4YvrfVn
            Z2WzfaoocQKZeDPanxuQqd5ZGsMRELXey3up7tgs23Jujh7YKDYZ8n6QozMhg03U
            aAEJAhBib1f0VArRoxl7OZr2nhoCMZbk5iApMbDD2QhVL0A4+q4fN0t1H+TB6FQv
            U7tKkb95hwjW/LB4u9M4j3sALaQVBCu+1bh/lNDAEam4txLuZSGSj0WLzGRdT7zh
            8AIFmBMHcqEs
            =Y3w+
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1lVSfA==,iv:FIaXK/0l8mCacLkQfT5gxxOF4xK2bO0cD3FxsmL3mrI=,tag:UmlzcocE4GgdMus0CaeeEg==,type:str]
    password: ENC[AES256_GCM,data:LUKJ12K6+q17qhTOghX1LQJ7M1DHetBXop/KzSNC,iv:cBV78Znk/oLbmfTmAg28GCiW2pgi86nuvvrTFoBcXaw=,tag:h1XVv7lajsmNKrUbqII3wA==,type:str]
sops:
    lastmodified: "2026-02-15T19:33:49Z"
    mac: ENC[AES256_GCM,data:mm5asp2XDI/lrTKKUHMq1UiLsEshbkWbrvVT2MXzfW+cicxWJ3AGlXKijJGkX9jq0+3R2AEA6i4gjhhkUp1PX9txcKwZO3PN2MwvGDDDhxXmrKQUnrNJ55AXQPx0BESMzY4dRdLu7io3zbu8rJq5qVqxazPyyX3WxYsarhUEZVE=,iv:nCAdASla5vJ0uGFcu4E0xfXsiB8iCSQCcVrbEhAyfI4=,tag:D/SI/Nbb6k0QNY/lICtgJQ==,type:str]
    pgp:
        - created_at: "2026-02-15T19:33:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAvhZ+eX2HrU0YppwaK0D0NJ0I6ju01feo1yZL1CwO9xv2
            wl1gPVFM5JzAAh2E2/u5/e4AhIbu7lh3sW04WE+1MmbdFLDND9q0im522U8KbdxA
            y7BXx/rapWyznM6OEvk10dDjBg67VJg6cldcf7K/YrJyienvsuwdQnuXRzWp/pvN
            8ENOUG5LdwLoKy0ysvJvd70tMIxF21Dek30mQKWoI+SegClY5PoNoJHhcA5sfq4l
            2I/Ydpez7N42NixrQfomQq2Mp+b6d/+sEehZqOf0pdt66V0cQNX0tF2iJvm1l8Q/
            7JqFFR5gDmdthSE6Ry/emGTRPEUU8D0JY2gd8yEya9i8vzfAYni2rRGyusKlLFJw
            R+7lR7uYVj4lwH4OCDfBlARioQnLzbhCjjy+fDxcg8B9S1u+U67YWeGrNE+pKKHf
            LIowMceLDRKmivvJ2GvanBHEw2wrO/BwZ72rw2ZlJVqs6HFdVvIozSHGf48s+Roq
            o7ijetbdUDZkPWZnogdgUFFowCSlCVS1Zqq8WQQaWKwd4FHezNiMSUowYRDS+8SP
            WzFV8Lx7P86gpJEBq0u/Kqsgt7KTLOuCjeAXV4QUD0/soVZtAta+dmKkp4YvrfVn
            Z2WzfaoocQKZeDPanxuQqd5ZGsMRELXey3up7tgs23Jujh7YKDYZ8n6QozMhg03U
            aAEJAhBib1f0VArRoxl7OZr2nhoCMZbk5iApMbDD2QhVL0A4+q4fN0t1H+TB6FQv
            U7tKkb95hwjW/LB4u9M4j3sALaQVBCu+1bh/lNDAEam4txLuZSGSj0WLzGRdT7zh
            8AIFmBMHcqEs
            =Y3w+
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-staging-basic-auth
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:u8ovOoi9KKkiC0wYcdXrdOszLlMKXabHCj7LJtTn0rmJMHiVADrD0+hD5Q==,iv:WWab0wMSsjlzbPmUmxNVtBgJ+GgFX+JfSqmuQUIso4s=,tag:U8wsb7n9aLQHuKGaWQ/AoQ==,type:str]
sops:
    lastmodified: "2026-02-15T19:33:49Z"
    mac: ENC[AES256_GCM,data:mm5asp2XDI/lrTKKUHMq1UiLsEshbkWbrvVT2MXzfW+cicxWJ3AGlXKijJGkX9jq0+3R2AEA6i4gjhhkUp1PX9txcKwZO3PN2MwvGDDDhxXmrKQUnrNJ55AXQPx0BESMzY4dRdLu7io3zbu8rJq5qVqxazPyyX3WxYsarhUEZVE=,iv:nCAdASla5vJ0uGFcu4E0xfXsiB8iCSQCcVrbEhAyfI4=,tag:D/SI/Nbb6k0QNY/lICtgJQ==,type:str]
    pgp:
        - created_at: "2026-02-15T19:33:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAvhZ+eX2HrU0YppwaK0D0NJ0I6ju01feo1yZL1CwO9xv2
            wl1gPVFM5JzAAh2E2/u5/e4AhIbu7lh3sW04WE+1MmbdFLDND9q0im522U8KbdxA
            y7BXx/rapWyznM6OEvk10dDjBg67VJg6cldcf7K/YrJyienvsuwdQnuXRzWp/pvN
            8ENOUG5LdwLoKy0ysvJvd70tMIxF21Dek30mQKWoI+SegClY5PoNoJHhcA5sfq4l
            2I/Ydpez7N42NixrQfomQq2Mp+b6d/+sEehZqOf0pdt66V0cQNX0tF2iJvm1l8Q/
            7JqFFR5gDmdthSE6Ry/emGTRPEUU8D0JY2gd8yEya9i8vzfAYni2rRGyusKlLFJw
            R+7lR7uYVj4lwH4OCDfBlARioQnLzbhCjjy+fDxcg8B9S1u+U67YWeGrNE+pKKHf
            LIowMceLDRKmivvJ2GvanBHEw2wrO/BwZ72rw2ZlJVqs6HFdVvIozSHGf48s+Roq
            o7ijetbdUDZkPWZnogdgUFFowCSlCVS1Zqq8WQQaWKwd4FHezNiMSUowYRDS+8SP
            WzFV8Lx7P86gpJEBq0u/Kqsgt7KTLOuCjeAXV4QUD0/soVZtAta+dmKkp4YvrfVn
            Z2WzfaoocQKZeDPanxuQqd5ZGsMRELXey3up7tgs23Jujh7YKDYZ8n6QozMhg03U
            aAEJAhBib1f0VArRoxl7OZr2nhoCMZbk5iApMbDD2QhVL0A4+q4fN0t1H+TB6FQv
            U7tKkb95hwjW/LB4u9M4j3sALaQVBCu+1bh/lNDAEam4txLuZSGSj0WLzGRdT7zh
            8AIFmBMHcqEs
            =Y3w+
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
