# Staging secrets â€” fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:PbsYtisRvTpsef5V9NNK/SpeK9Pmt1RRwI/anpmRrA9NMSYFJ+noxwCtCyO+QbGZ5FFn,iv:IXKmeOqG3ZKLwdvpBm3nw2XDnUAAbDUQIce+qmxh8Dk=,tag:ZRjVMy1jm4ZFZwjwrt/MkQ==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:fV8reQESfz59,iv:JTUCTNR+8qMrVUqAancANQS0QskXyMrhQSlntFODpR0=,tag:3Hxh9D8qTpGUq8cOfQxzlw==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:I+7RaUNh4doPJCpKUzTKWAcJbqc2p6knpsTGlQPK,iv:hT0T9vkQl9ZtSwKvsNWRgjh/WK/z9NpPIgm4O9ZJh90=,tag:0PMe4TCXsejL+Luf2qHFnw==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:gH6x4aGnL7vH,iv:WuTbcW14QNtUeo5zqEJDvdK5QfP8nEhqQUTjoXYcX84=,tag:KdzYhJdwWiZGZm+Zm+vw5w==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:dNiYHQgqhD6zlw==,iv:jprENdu907nIL1ywI0/QCUMQQyNVj/WGY5f+5ECjNvk=,tag:z7pRBq1TJ6oeirV4xD6adw==,type:str]
sops:
    lastmodified: "2026-02-28T20:05:28Z"
    mac: ENC[AES256_GCM,data:6mZr7FfiGYivRWGN1dI02ikekvPnyiqWUQQA2cb+Wc6kUbtdPDVh2WRJErjV0KICcJKv3G+zm4Yxc4mb+80XfIYqtILukTsZCJDlDYJMlTAsgA6uCArS5Z3WULaKHVDiFKz/RSufLC2kjCJVceY8/bZtc/ndB15q6AbR/yh716I=,iv:DJImJfW2IrSFrm3NA3MF6I9cquyVXk8QoXoZ/7WpNeI=,tag:p30scU4LBldwd4mQ0jV1Ng==,type:str]
    pgp:
        - created_at: "2026-02-28T20:05:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAlXEVFn/uTyAuDV6FyiOaGAQuKT78leoruGgwco8q4NJ+
            whnvR0I2ddBWwae1jRyxcJd+SSpHZa1E6sK6Oa4NaWz37ciQ0I/WHW2xZC89xi7d
            dnzLLAZOP0Yj9W1zDO/rr8YKrp3pkspC8KDyW+uGvVTOHXPls3HfnNgNbO3ikJEh
            kg2aCAzTLKKWcivzQS9R9No4ehMDPBaQuCT33ZHTX+wYeMnAGJILVqab/tFjr8Ah
            bcpPl6pXah3+Nn7/sx+CY+ya+ThQ23ZS3JZPHUFl52LHxlyjBQiOoSP2huN0YkSv
            SQ9EKdm/OmrKy0knwL3/zQjPeCK57ZhTust/dTekJ0yiOARCD8Eqd1ZBHC6iTTaO
            h4WdQ3v3TkCmBUpTaOmYUHvVqcX0IWfSXbGPb2lBNBzPx2v3H1TbWMhReBMqzfN5
            c4rI1Lise2ShwX6n9K6uyu5PuunzB1O9B8DT1FuIQtTs2yyPPtK+JlFN54iq7xZ6
            tsZ0z6jKAoWw1+9J6FqK4g0T2vaBJe7S5co7tha04+wejM2SI1dfKAuvUFSNSUnd
            DqCktzTkpms6I+AnpsBF/37dSNu8hRZQzIbUvLI7arUPtNtBBhq/PNoROv14eKX5
            RW/fnynq7bv3Gj5FAgLcxWJOqP99LlzVXZZBVZJ72Ns807F26ZgHqcSGzcrbvSXU
            aAEJAhCo96wf/hajhW/lYglFzlCqxEyDlDeGYDyAkFuNyHrAjMyFOiHYgFmfx6i1
            aHDBHtM2kEA2pAOLH/htvmlRDj/XQE2z76I8eq28ttpTx7ynpqxEqsWZvy6CsIQ7
            nXntmZNZUWcV
            =nvhM
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qtPEh/f05iNS,iv:rbj5nHOV5N4L+U5M7kEZ0NCrS0eQJ8C/6XpW7VyG7Xw=,tag:wFyUtv1peWeUzJ6JjxkhPg==,type:str]
    password: ENC[AES256_GCM,data:Dcjsf8jO/sWqT4qPxpC+A8PK0Cu2CidsFUhT1nZP,iv:rQTo+LzzzDcuQT0bA/QDPMf4HtMc3VKMj6hw6pP36c4=,tag:JZD4kjVQg7y2FDdNERjASg==,type:str]
sops:
    lastmodified: "2026-02-28T20:05:28Z"
    mac: ENC[AES256_GCM,data:6mZr7FfiGYivRWGN1dI02ikekvPnyiqWUQQA2cb+Wc6kUbtdPDVh2WRJErjV0KICcJKv3G+zm4Yxc4mb+80XfIYqtILukTsZCJDlDYJMlTAsgA6uCArS5Z3WULaKHVDiFKz/RSufLC2kjCJVceY8/bZtc/ndB15q6AbR/yh716I=,iv:DJImJfW2IrSFrm3NA3MF6I9cquyVXk8QoXoZ/7WpNeI=,tag:p30scU4LBldwd4mQ0jV1Ng==,type:str]
    pgp:
        - created_at: "2026-02-28T20:05:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAlXEVFn/uTyAuDV6FyiOaGAQuKT78leoruGgwco8q4NJ+
            whnvR0I2ddBWwae1jRyxcJd+SSpHZa1E6sK6Oa4NaWz37ciQ0I/WHW2xZC89xi7d
            dnzLLAZOP0Yj9W1zDO/rr8YKrp3pkspC8KDyW+uGvVTOHXPls3HfnNgNbO3ikJEh
            kg2aCAzTLKKWcivzQS9R9No4ehMDPBaQuCT33ZHTX+wYeMnAGJILVqab/tFjr8Ah
            bcpPl6pXah3+Nn7/sx+CY+ya+ThQ23ZS3JZPHUFl52LHxlyjBQiOoSP2huN0YkSv
            SQ9EKdm/OmrKy0knwL3/zQjPeCK57ZhTust/dTekJ0yiOARCD8Eqd1ZBHC6iTTaO
            h4WdQ3v3TkCmBUpTaOmYUHvVqcX0IWfSXbGPb2lBNBzPx2v3H1TbWMhReBMqzfN5
            c4rI1Lise2ShwX6n9K6uyu5PuunzB1O9B8DT1FuIQtTs2yyPPtK+JlFN54iq7xZ6
            tsZ0z6jKAoWw1+9J6FqK4g0T2vaBJe7S5co7tha04+wejM2SI1dfKAuvUFSNSUnd
            DqCktzTkpms6I+AnpsBF/37dSNu8hRZQzIbUvLI7arUPtNtBBhq/PNoROv14eKX5
            RW/fnynq7bv3Gj5FAgLcxWJOqP99LlzVXZZBVZJ72Ns807F26ZgHqcSGzcrbvSXU
            aAEJAhCo96wf/hajhW/lYglFzlCqxEyDlDeGYDyAkFuNyHrAjMyFOiHYgFmfx6i1
            aHDBHtM2kEA2pAOLH/htvmlRDj/XQE2z76I8eq28ttpTx7ynpqxEqsWZvy6CsIQ7
            nXntmZNZUWcV
            =nvhM
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-staging-basic-auth
type: Opaque
# htpasswd format: user:$apr1$...
stringData:
    users: ENC[AES256_GCM,data:JXfkWMaBZpkgtyoG0n7hTmCvHjlmmayER5DdK5nw6sajf7hEwLE+mTYTyolNMMo=,iv:dPEc4Idn+w8Mad/7Tvk1Dg5ZSiRvS8+jqO/lxl+9dVE=,tag:w0GBGiadp8NqKOTcdYYV2w==,type:str]
sops:
    lastmodified: "2026-02-28T20:05:28Z"
    mac: ENC[AES256_GCM,data:6mZr7FfiGYivRWGN1dI02ikekvPnyiqWUQQA2cb+Wc6kUbtdPDVh2WRJErjV0KICcJKv3G+zm4Yxc4mb+80XfIYqtILukTsZCJDlDYJMlTAsgA6uCArS5Z3WULaKHVDiFKz/RSufLC2kjCJVceY8/bZtc/ndB15q6AbR/yh716I=,iv:DJImJfW2IrSFrm3NA3MF6I9cquyVXk8QoXoZ/7WpNeI=,tag:p30scU4LBldwd4mQ0jV1Ng==,type:str]
    pgp:
        - created_at: "2026-02-28T20:05:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAlXEVFn/uTyAuDV6FyiOaGAQuKT78leoruGgwco8q4NJ+
            whnvR0I2ddBWwae1jRyxcJd+SSpHZa1E6sK6Oa4NaWz37ciQ0I/WHW2xZC89xi7d
            dnzLLAZOP0Yj9W1zDO/rr8YKrp3pkspC8KDyW+uGvVTOHXPls3HfnNgNbO3ikJEh
            kg2aCAzTLKKWcivzQS9R9No4ehMDPBaQuCT33ZHTX+wYeMnAGJILVqab/tFjr8Ah
            bcpPl6pXah3+Nn7/sx+CY+ya+ThQ23ZS3JZPHUFl52LHxlyjBQiOoSP2huN0YkSv
            SQ9EKdm/OmrKy0knwL3/zQjPeCK57ZhTust/dTekJ0yiOARCD8Eqd1ZBHC6iTTaO
            h4WdQ3v3TkCmBUpTaOmYUHvVqcX0IWfSXbGPb2lBNBzPx2v3H1TbWMhReBMqzfN5
            c4rI1Lise2ShwX6n9K6uyu5PuunzB1O9B8DT1FuIQtTs2yyPPtK+JlFN54iq7xZ6
            tsZ0z6jKAoWw1+9J6FqK4g0T2vaBJe7S5co7tha04+wejM2SI1dfKAuvUFSNSUnd
            DqCktzTkpms6I+AnpsBF/37dSNu8hRZQzIbUvLI7arUPtNtBBhq/PNoROv14eKX5
            RW/fnynq7bv3Gj5FAgLcxWJOqP99LlzVXZZBVZJ72Ns807F26ZgHqcSGzcrbvSXU
            aAEJAhCo96wf/hajhW/lYglFzlCqxEyDlDeGYDyAkFuNyHrAjMyFOiHYgFmfx6i1
            aHDBHtM2kEA2pAOLH/htvmlRDj/XQE2z76I8eq28ttpTx7ynpqxEqsWZvy6CsIQ7
            nXntmZNZUWcV
            =nvhM
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
